import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import { outfit } from "./fonts";
import "./globals.css";
import Header from "./components/Header";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-black w-full"
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
